export const ACTION = {
  SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
  RESET: "RESET",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_MY_PRODUCTS: "GET_MY_PRODUCTS",
  SET_NEW_PRODUCT: "SET_NEW_PRODUCT",
  GET_USERLIST: "GET_USERLIST",
  SET_SEARCHED_PRODUCTS: "SET_SEARCHED_PRODUCTS",
};
